export { default as Auth } from "./auth/Auth"
export { default as Home } from "./home/Home"
export { default as Settings } from "./settings/Settings"
export { default as Profile } from "./profile/Profile"
export { default as Statistics } from "./statistics/Statistics"
